ControleBiblioteca/Controllers/ColaboradorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ControleBiblioteca.Models;

namespace ControleBiblioteca.Controllers
{
    public class ColaboradorController : Controller
    {
        public ActionResult Index()
        {
            return View(ColaboradorREP.Colabs);
        }

        public ActionResult Cadastrar()
        {
            return View();
        }

        public ActionResult Detalhes(int id)
        {
            var colabor = ColaboradorREP.Colabs.FirstOrDefault(n => n.IdColaborador == id);
            return View(colabor);
        }


        public ActionResult Alterar(int id)
        {
            var colabor = ColaboradorREP.Colabs.FirstOrDefault(n => n.IdColaborador == id);
            return View(colabor);
        }




    }
}

ControleBiblioteca/Controllers/UnidadeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ControleBiblioteca.Models;

namespace ControleBiblioteca.Controllers
{
    public class UnidadeController : Controller
    {
        // GET: Livros
        public ActionResult Index()
        {
            return View(UnidadeREP.Uni);
        }

        public ActionResult Cadastrar()
        {
            return View();
        }

        public ActionResult Detalhes(int id)
        {
            var uni = UnidadeREP.Uni.FirstOrDefault(n => n.IdUnidade == id);
            return View(uni);
        }


        public ActionResult Alterar(int id)
        {
            var uni = UnidadeREP.Uni.FirstOrDefault(n => n.IdUnidade == id);
            return View(uni);
        }




    }
}

ControleBiblioteca/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Biblioteca Fit</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="container">
        <div class="jumbotron">
            <h1>FIT - Controle da Biblioteca</h1>
        </div>

        <div class="navbar navbar-inverse">
            <div class="container">
                <div class="navbar-header">
                    @Html.ActionLink("Livros", "Index", "Livros", null, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-header">
                    @Html.ActionLink("Colaboradores", "Index", "Colaborador", null, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-header">
                    @Html.ActionLink("Unidades", "Index", "Unidade", null, new { @class = "navbar-brand" })
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-9">
                @RenderBody()
            </div>
            @*<div class="col-md-3">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <p class="panel-title">Buscar notícias</p>
                    </div>
                    <div class="panel-body">
                        @using (Html.BeginForm("Buscar", "Noticias", FormMethod.Get))
                        {
                            <input type="text" class="form-control" name="texto" placeholder="Buscar por..." />
                        }
                    </div>
                </div>
            </div>*@
        </div>

        <hr />

        <footer>
            <p>&copy; @DateTime.Now.Year - FIT </p>
        </footer>
    </div>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>