ControleBiblioteca/Models/Livros.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ControleBiblioteca.Models
{
    public class Livros
    {
        [Display(Name = "Código de barra")]
        public int IdCodBarra { get; set; }

        [Display(Name = "Status do livro")]
        public string Status { get; set; }

        [Display(Name = "Data de Cadastro")]
        public DateTime DtCadastro { get; set; }

        [Display(Name = "Nome do livro")]
        public string NomeLivro { get; set; }

        [Display(Name = "Data de publicação")]
        public DateTime DtPublicacao { get; set; }

        [Display(Name = "Quantidade de páginas")]
        public int QtdPaginas { get; set; }

        [Display(Name = "Nome do autor")]
        public string Autor { get; set; }

        [Display(Name = "Imagem")]
        public string ImgCapa { get; set; }

        [Display(Name = "Unidade")]
        public string Unidade { get; set; }
    }
}

ControleBiblioteca/Controllers/LivrosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ControleBiblioteca.Models;

namespace ControleBiblioteca.Controllers
{
    public class LivrosController : Controller
    {
        // GET: Livros
        public ActionResult Index()
        {
            return View(LivrosREP.Livro);
        }

        public ActionResult Cadastrar()
        {
            return View();
        }

        public ActionResult Detalhes(int id)
        {
            var livroo = LivrosREP.Livro.FirstOrDefault(n => n.IdCodBarra == id);
            return View(livroo);
        }


        public ActionResult Alterar(int id)
        {
            var livroo = LivrosREP.Livro.FirstOrDefault(n => n.IdCodBarra == id);
            return View(livroo);
        }




    }
}

ControleBiblioteca/Views/Livros/Alterar.cshtml
@model ControleBiblioteca.Models.Livros

@{
    ViewBag.Title = "Alterar";
}

<h2></h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Alterar Cadastro</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.IdCodBarra, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.IdCodBarra, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.IdCodBarra, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Status, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DtCadastro, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DtCadastro, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DtCadastro, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.NomeLivro, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.NomeLivro, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.NomeLivro, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DtPublicacao, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DtPublicacao, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DtPublicacao, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.QtdPaginas, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.QtdPaginas, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.QtdPaginas, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Autor, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Autor, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Autor, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ImgCapa, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ImgCapa, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ImgCapa, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Unidade, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Unidade, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Unidade, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Voltar", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

ControleBiblioteca/Views/Livros/Cadastrar.cshtml
@model ControleBiblioteca.Models.Livros

@*@{
    ViewBag.Title = "Cadastrar";
}

<h2>Cadastrar Livro</h2>*@


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Cadastrar Livro</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.IdCodBarra, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.IdCodBarra, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.IdCodBarra, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Status, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DtCadastro, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DtCadastro, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DtCadastro, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.NomeLivro, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.NomeLivro, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.NomeLivro, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DtPublicacao, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DtPublicacao, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DtPublicacao, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.QtdPaginas, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.QtdPaginas, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.QtdPaginas, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Autor, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Autor, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Autor, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ImgCapa, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ImgCapa, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ImgCapa, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Unidade, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Unidade, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Unidade, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Voltar", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

ControleBiblioteca/Views/Livros/Detalhes.cshtml
@model ControleBiblioteca.Models.Livros

@*@{
    ViewBag.Title = "Detalhes";
}*@


<div>
    <h4>Detalhes do Livro</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.IdCodBarra)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IdCodBarra)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DtCadastro)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DtCadastro)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NomeLivro)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NomeLivro)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DtPublicacao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DtPublicacao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.QtdPaginas)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.QtdPaginas)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Autor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Autor)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Unidade)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Unidade)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImgCapa)
        </dt>

        <dd>
            @if (Model.IdCodBarra == 01010)
            {
                <img src="~/Images/monge_.jpg" height="100px" width="70px" />
            }

            @if (Model.IdCodBarra == 02020)
            {
                <img src="~/Images/estrelas.jpg" height="100px" width="70px" />
            }

            @if (Model.IdCodBarra == 030303)
            {
                <img src="~/Images/espada.jpg" height="100px" width="70px" />
            }

            @if (Model.IdCodBarra == 040404)
            {
                <img src="~/Images/principe.jpg" height="100px" width="70px" />
            }
            @*@Html.DisplayFor(model => model.Im)*@
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Alterar", "Livros", new { @id = Model.IdCodBarra }) |
    @Html.ActionLink("Voltar", "Index")
</p>

ControleBiblioteca/Views/Livros/Index.cshtml
@model IEnumerable<ControleBiblioteca.Models.Livros>

@*@{
    ViewBag.Title = "Index";
}*@

<p>
    @Html.ActionLink("Cadastro de livro", "Cadastrar", null, new { @class = "btn btn-primary" })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.IdCodBarra)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Status)
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.DtCadastro)
        </th>*@
        <th>
            @Html.DisplayNameFor(model => model.NomeLivro)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DtPublicacao)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.QtdPaginas)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Autor)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Unidade)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.IdCodBarra)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Status)
        </td>
        @*<td>
            @Html.DisplayFor(modelItem => item.DtCadastro)
        </td>*@
        <td>
            @Html.DisplayFor(modelItem => item.NomeLivro)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DtPublicacao)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.QtdPaginas)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Autor)
        </td>
        <th>
            @Html.DisplayFor(modelItem => item.Unidade)
        </th>
        <td>
            @Html.ActionLink("Alterar", "Alterar", new { id = item.IdCodBarra }) |
            @Html.ActionLink("Detalhes", "Detalhes", new { id = item.IdCodBarra }) |
            @*@Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })*@
        </td>
    </tr>
}

</table>